## 使用mysql 将 application.yml 文件的 datasource 部分替换， 更改url, username 和 password
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_base?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource